[alias]
dependencies = "run --package tools --bin dependencies"
syntax = "run --package tools --bin syntax"
coverage = "run --package tools --bin coverage"
vulnerabilities = "run --package tools --bin vulnerabilities"
